version: '3.9'
services:
  api:
    container_name: Hausboot-Api
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    ports:
      - '3100:3100'
  client:
    container_name: Hausboot-Frontend
    env_file: ./client/.env
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - '3000:3000'
  nginx:
    depends_on:
      - api
      - client
    container_name: Hausboot-Server
    restart: always
    build:
      dockerfile: Dockerfile
      network: host
      context: ./nginx
      args:
        - CERTBOT_EMAIL=admin@xn--teichland-kapitne-4qb.de #replace with your own email
        - DOMAIN_LIST=xn--teichland-kapitne-4qb.de,www.xn--teichland-kapitne-4qb.de #replace with your own domains
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/letsencrypt:/etc/letsencrypt
    ports:
      - '80:80'
      - '443:443'
