version: '3.5'
services:
  db:
    container_name: Hausboot-Database
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=prisma
      - DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/prisma"
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
  api:
    depends_on:
      - db
    container_name: Hausboot-Api
    build:
      context: ./api
      args:
        GOOGLE_CALENDAR_ID: ${GOOGLE_CALENDAR_ID}
        MAILP: ${MAILP}
    ports:
      - '3100:3100'
  client:
    container_name: Hausboot-Frontend
    build:
      context: ./client
      args:
        REACT_APP_GOOGLE_API_KEY: ${REACT_APP_GOOGLE_API_KEY}
        REACT_APP_USERNAME: ${REACT_APP_USERNAME}
        REACT_APP_PASSWORD: ${REACT_APP_PASSWORD}
    ports:
      - '3000:3000'
  nginx:
    depends_on:
      - api
      - client
    container_name: Hausboot-Server
    restart: always
    build:
      network: host
      context: ./nginx
      args:
        - CERTBOT_EMAIL=admin@xn--teichland-kapitne-4qb.de #replace with your own email
        - DOMAIN_LIST=xn--teichland-kapitne-4qb.de,www.xn--teichland-kapitne-4qb.de #replace with your own domains
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - letsencrypt:/etc/letsencrypt
    ports:
      - '80:80'
      - '443:443'
volumes:
  letsencrypt:
  db:
