version: '3.4'
services:
  api:
    container_name: Hausboot-Api
    environment:
      - REACT_APP_GOOGLE_CALENDAR_ID
    build:
      context: ./api
    ports:
      - '3100:3100'
  client:
    container_name: Hausboot-Frontend
    environment:
      - REACT_APP_GOOGLE_API_KEY
      - REACT_APP_GOOGLE_CALENDAR_ID
    build:
      context: ./client
    ports:
      - '3000:3000'
  nginx:
    depends_on:
      - api
      - client
    container_name: Hausboot-Server
    restart: always
    build:
      network: host
      context: ./nginx
      args:
        - CERTBOT_EMAIL=admin@xn--teichland-kapitne-4qb.de #replace with your own email
        - DOMAIN_LIST=xn--teichland-kapitne-4qb.de,www.xn--teichland-kapitne-4qb.de #replace with your own domains
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - letsencrypt:/etc/letsencrypt
    ports:
      - '80:80'
      - '443:443'
networks:
  host:
    external: true
volumes:
  letsencrypt:
