# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_SERVERNAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" -p ${{ secrets.REGISTRY_SERVERNAME }}.azurecr.io/hausbootdev:latest up -d --build
      - run: docker-compose push ${{ secrets.REGISTRY_SERVERNAME }}.azurecr.io/hausbootdev:latest
## This section should be commented for now as we haven't created the Azure web app yet
# - uses: azure/login@v1
#   with:
#    creds: ${{ secrets.AZURE_CREDENTIALS }}
# - uses: azure/webapps-container-deploy@v1
#   with:
#    app-name: 'GithubDotNetCoreContainer'
#    images: '${{ secrets.REGISTRY_SERVERNAME }}.azurecr.io/githubwebapp:${{ github.sha }}'
#
# - name: Azure logout
#   run: |
#     az logout
